import Footer from '@anwaa/components/footer/Footer';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@anwaa/components/navbar/Navbar';
import { ThemeProvider } from '@anwaa/context/ThemeContext';
import AuthProvider from '@anwaa/components/AuthProvider/AuthProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Anwaar App',
  description: 'Generated by Muhammad Anwaar',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <ThemeProvider>
        <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
        </body>
    </html>
  )
}
